# Setup
title: Jing Peng
description:  >
  Hi, I am Jing Peng（彭景）. I am now a Ph.D. student at
  <a href="https://x-lance.sjtu.edu.cn/" target="_blank" rel="noopener">X-LANCE Lab</a>
  of Shanghai Jiao Tong University, supervised by
  <a href="https://www.cs.sjtu.edu.cn/en/jiaoshiml/yukai.html" target="_blank" rel="noopener">Prof. Kai Yu</a>.
url: https://pigeondan1.github.io
avatar: /life_photo.jpg
paginate: 5
permalink: pretty
cover_image: /moutain.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: Jing Peng
  card: summary
logo: logo.png
social:
  name: Jing Peng
  links:
    - https://github.com/PigeonDan1
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Songzi Vong
  url: https://github.com/vszhub/
  email: vszhub@gmail.com
